### ISSUE TITLE
Console Log Websocket Error?

### ISSUE THREAD

**Issue by m-korkut** [Pitchlyapp/meteor-apollo2#1]
Hello,
Thank you for good example.
This example work good but I get an console log error. This error;

WebSocket connection to 'ws://localhost:3000/sockjs/127/1vebnsci/websocket' failed: Connection closed before receiving a handshake response 
SockJS.websocket @ sockjs-0.3.4.js:1275 line

**Comment by michaelcbrook** [comment]
That is referring to Meteor's built-in websocket connection. The GraphQL one should still work just fine. I did look up this issue, though, as it's still not desirable. I'm having surgery in a couple days so I don't have time to test it right now, but a possible solution might be here:

https://github.com/apollographql/subscriptions-transport-ws/issues/235

Let me know if you get it working, I'd appreciate it. Otherwise, I'll try it myself when I get back.

**Comment by michaelcbrook** [comment]
Update on this:

I did try to get the example in the link working, but couldn't successfully. At any rate, I did test whether Meteor subscriptions and GraphQL subscribe work together successfully despite the error, and they do. So there doesn't seem to be any reason to worry about it.

**Comment by michaelcbrook** [comment]
**Update again:**

About a year later and I got a solution working finally. I had to do this so I could inspect Meteor's websocket frames. This error was preventing me from doing so. The code I got working is below. Note the comments for parts that I added/changed. (Not everything here is required. I just shared my whole server code.)

```javascript
import { Meteor } from 'meteor/meteor';
import { WebApp } from 'meteor/webapp';
import { execute, subscribe } from 'graphql';
import { SubscriptionServer } from 'subscriptions-transport-ws';
import { createApolloServer, addCurrentUserToContext } from 'meteor/apollo';
import { formatError } from 'apollo-errors';
import cors from 'cors';
import { parse as urlParse } from 'url'; //********** < add this **********

import { makeExecutableSchema } from 'graphql-tools';
import resolvers from './resolvers.js';
import rawSchema from './schema.graphql';

const schema = makeExecutableSchema({
  typeDefs: rawSchema,
  resolvers
});

// any additional context you use for your resolvers, if any
const context = {};

// start a graphql server with Express handling a possible Meteor current user
createApolloServer({ 
  schema,
  context,
  formatError
}, {
  //enable access to GraphQL API cross-domain
  configServer: expressServer => expressServer.use(cors()),
  graphiql: !!Meteor.isDevelopment //only show graphiql when in development environment
});

const subscriptionServer = new SubscriptionServer({
  schema,
  execute,
  subscribe
}, {
  noServer: true //********** < won't work unless you do this **********
});

//********** add all below **********
//********** this prevents websocket conflicts between GraphQL and Meteor **********

// Generate upgrade handler which supports both Meteor socket and graphql.

const wsServer = subscriptionServer['wsServer'];

const upgradeHandler = (req, socket, head) => {
  const pathname = urlParse(req.url).pathname;
  if (pathname==="/subscriptions") {
    wsServer.handleUpgrade(req, socket, head, (ws) => {
      wsServer.emit('connection', ws, req);
    });
  } else if ( pathname.startsWith('/sockjs') ) {
    // Don't do anything, this is meteor socket.
  } else {
    socket.destroy();
  }
};

WebApp.httpServer.on('upgrade', upgradeHandler);
```

You'll need to do a quick `meteor npm install --save url` and you're done.

Note that this won't work for the newest Apollo version, where `subscriptions` is defined in `ApolloServer` instantiation. I haven't figured out how to make it work with the newest version, so you may need to stick with Apollo 1.0 for now.

**Comment by imhazige** [comment]
Yes, I have the same problem when integrate with apollo server v3.
