### ISSUE TITLE
Adding data subscription operations

### ISSUE THREAD

**Issue by m-korkut** [Pitchlyapp/meteor-apollo2#2]
I am  use "subscribeToMore"  to insert data in subscribe process.I am Can't subscription.Could you show an example of subscription for inclusion?

**Comment by michaelcbrook** [comment]
I don't have any examples off hand, as I haven't done this yet myself. But I will be in a project of mine soon. My first thought would be to wrap the queries in the `OnCreated` function in `this.autorun` and make the variables to the queries reactive. If it requires something different, I'll try to update here to help.
