### ISSUE TITLE
`TypeError: Cache is not a constructor` in main.js?

### ISSUE THREAD

**Issue by VikR0001** [Pitchlyapp/meteor-apollo2#4]
Thanks for putting this demo app together!

I've run `meteor npm install` and also just to double-check, `npm install apollo-cache-inmemory --save`. Subscriptions are not yet working, and I'm seeing this in the console log:

```
main.js:45 Uncaught TypeError: Cache is not a constructor
    at main.js (main.js:45)
    at fileEvaluate (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:343)
    at require (modules-runtime.js?hash=8587d188e038b75ecd27ed2469a52b269e38fb62:238)
    at app.js?hash=8f2a8f9f2e7814f54e97811c8033c43ac3dc3a36:398
```
How can I correct this error?

Thanks very much in advance.

**Comment by VikR0001** [comment]
Fixed it:

Updated `import Cache from 'apollo-cache-inmemory';` to `import { InMemoryCache } from 'apollo-cache-inmemory'`

I also had to change `const cache = new Cache(window.__APOLLO_STATE);` to `const cache = new InMemoryCache();` to avoid getting an `illegal constructor` error. 

Is there a way to use `window.__APOLLO_STATE` with `InMemoryCache`?

**Comment by VikR0001** [comment]
Update -- `window.__APOLLO_STATE` doesn't appear to exist in the demo app at the time this line is called. 

Okay, with your help I now have a demo app for Apollo 2.0. Thank you very much!

**Comment by michaelcbrook** [comment]
@VikR0001 This is correct. The new updates must have broken the Cache import. The code and readme have been changed to reflect the new changes! Thanks for pointing this out!

**Comment by VikR0001** [comment]
You're very welcome, Michael.
